In [2]:
import torch
print(torch.__version__)

2.11.0+cu128


In [3]:
if torch.cuda.is_available():
  print("gpu is available")
  print(f"using gpu:{torch.cuda.get_device_name(0)}")
else:
  print("gpu not available.using cpu ")

gpu is available
using gpu:Tesla T4


CREATING A TENSOR

In [4]:
#using empty
a=torch.empty(2,3)
type(a)

torch.Tensor

In [10]:
#using zeros/ones/rand
torch.zeros(2,3)
torch.ones(2 ,3)
torch.rand(2 ,3)

tensor([[0.5675, 0.4361, 0.6341],
        [0.1335, 0.7656, 0.0413]])

In [11]:
#manual seed for reproducibiltiy
# generate same random values anytime if seed is kept same
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
#other functions
print("using arange->" ,torch.arange(0,10,2))# integer values
print("using linspace->",torch.linspace(0,10,10)) #evenly space valus in range
print("using eye->",torch.eye(5)) # 5*5 identity matrix
print("using full->",torch.full((3,3),5))

using arange-> tensor([0, 2, 4, 6, 8])
using linspace-> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye-> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full-> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [16]:
#shape find karlo
a.shape

torch.Size([2, 3])

In [17]:
# this creates a tensor of same dimention,with values we want
torch.empty_like(a)
torch.zeros_like(a)
torch.ones_like(a)


tensor([[1., 1., 1.],
        [1., 1., 1.]])

TENSOR DATA TYPES

In [21]:
#find data tytpes
a.dtype

torch.float32

In [23]:
# assign data type
torch.tensor([1,0,2.5,3.0],dtype=torch.int32)

tensor([1, 0, 2, 3], dtype=torch.int32)

MATHEMATICAL OPERATIONS


In [28]:
# scalar operation
x=torch.rand(2,2)
x

tensor([[0.4183, 0.9014],
        [0.9969, 0.7565]])

In [32]:
#addition/substraction/multiplication/division/int_division/mod/power
x+2
x-2
x*3
x/3
x//3
x%2
x**2

tensor([[0.1750, 0.8125],
        [0.9938, 0.5723]])

In [33]:
# if twon tensor of same shape
# (a+b )(A-B)like that


In [37]:
c=torch.tensor([1.2,-2.3,3.5,-4.4])
torch.abs(c)
torch.round(c)
torch.ceil(c)
torch.round(c)


tensor([ 1., -2.,  4., -4.])

In [39]:
#clamp
torch.clamp(c,min=2,max=3)

tensor([2., 2., 3., 2.])

REDUCTION OPERATION

In [47]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[7., 0., 0.],
        [9., 5., 7.]])

In [48]:
torch.sum(e) #sum of all elements
torch.sum(e,dim=0)  # sum of all columns
torch.sum(e,dim=1)  # sum  of rows
torch.mean(e)
# mean just same as  sum
# use dim=0 for columns mean and  (1 for rows mean)
torch.meadian(e)
torch.prod(e)
torch.var(e)


tensor(4.6667)

In [ ]:
torch.det(h)
torch.inverse(h)

COMPARISON operation

In [49]:
A=torch.randint(size=(2,3),low=0,high=10)
B=torch.randint(size=(2,3),low=0,high=10)
print(A)
print(B)

tensor([[3, 9, 4],
        [0, 5, 7]])
tensor([[5, 9, 9],
        [7, 5, 9]])


In [50]:
A>B
#similary
# equalto not enqualto  etc etc

tensor([[False, False, False],
        [False, False, False]])

In [ ]:
# calcluate log/exp/sqrt/sigmoid
torch.log(A)
torch.exp(A)
torch.sqrt(A)
torch.sigmoid(A)

IMPLACE OPERATIONS


In [54]:
m=torch.randint(size=(2,3),low=2,high=10)
n=torch.randint(size=(2,3),low=2,high=10)
print(m)
print(n)
# I can use
m.add_(n) # to store the values  in m after addition
print(m)

tensor([[4, 2, 2],
        [4, 7, 4]])
tensor([[3, 2, 7],
        [4, 8, 3]])
tensor([[ 7,  4,  9],
        [ 8, 15,  7]])


COPYING A TENSOR

In [55]:
a=torch.rand(2,3)
a

tensor([[0.9516, 0.2855, 0.2324],
        [0.9141, 0.7668, 0.1659]])

COMPARING [GPU] AND [CPU]

In [59]:
b=a  # b is a copy of a
# but if now you change anything in a ,then the smae change is copied in b also
# which we don't want
# id(a)=id(b)
b1=a.clone()  #this avoids that problem
print(id(b)==id(a))
print(id(b1)==id(a))

True
False


In [1]:
import torch
import time

# 1. Define the size of the square matrices
# A size of 5000x5000 creates a heavy mathematical workload to really test the hardware.
matrix_size = 20000

print(f"Generating random {matrix_size}x{matrix_size} matrices...")

# 2. Benchmark on CPU
# We create random matrices on the host memory (RAM) and compute on the CPU
matrix_cpu1 = torch.randn(matrix_size, matrix_size)
matrix_cpu2 = torch.randn(matrix_size, matrix_size)

print("Starting CPU calculation...")
start_time_cpu = time.time()

# Perform matrix multiplication on CPU
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)

cpu_duration = time.time() - start_time_cpu
print(f"Time taken on CPU: {cpu_duration:.4f} seconds\n")


# 3. Benchmark on GPU
# We check if a CUDA-capable GPU (like a Tesla T4) is available
if torch.cuda.is_available():
    print(f"GPU Found: {torch.cuda.get_device_name(0)}")

    # Move the matrices from system RAM over to the GPU VRAM
    matrix_gpu1 = matrix_cpu1.to('cuda')
    matrix_gpu2 = matrix_cpu2.to('cuda')

    print("Starting GPU calculation...")
    start_time_gpu = time.time()

    # Perform matrix multiplication on GPU
    result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)

    # CRITICAL STEP: PyTorch executes GPU operations asynchronously.
    # torch.cuda.synchronize() forces Python to wait until the GPU completely finishes
    # the math before recording the stop time.
    torch.cuda.synchronize()

    gpu_duration = time.time() - start_time_gpu
    print(f"Time taken on GPU: {gpu_duration:.4f} seconds\n")

    # 4. Compare Results
    speedup = cpu_duration / gpu_duration
    print("-" * 40)
    print(f"⚡ RESULT: The GPU is {speedup:.2f}x FASTER than the CPU! ⚡")
    print("-" * 40)
else:
    print("❌ No GPU detected! Please go to Runtime -> Change runtime type and select a GPU.")

Generating random 20000x20000 matrices...
Starting CPU calculation...
Time taken on CPU: 128.4586 seconds

GPU Found: Tesla T4
Starting GPU calculation...
Time taken on GPU: 3.6120 seconds

----------------------------------------
⚡ RESULT: The GPU is 35.56x FASTER than the CPU! ⚡
----------------------------------------
